# Generated by Django 5.0.4 on 2024-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(max_length=100)),
                ('email_pengguna', models.EmailField(max_length=254, unique=True)),
                ('password_pengguna', models.CharField(max_length=100)),
                ('total_dzikir', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
    ]
