# Generated by Django 5.0.4 on 2024-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileFlutter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dzikir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_dzikir', models.IntegerField(default=0)),
                ('recent_dzikir', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dzikir',
            },
        ),
    ]
