# Generated by Django 5.0.4 on 2024-07-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileFlutter', '0002_dzikir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True},
        ),
    ]
