# Generated by Django 5.0.4 on 2024-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MobileFlutter', '0004_delete_dzikir_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailPengguna',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id_detailpengguna', models.AutoField(primary_key=True, serialize=False)),
                ('total_dzikir', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'detail_pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
    ]
